#3 services
version: '3.9'
services:
  mysql:
    image: mysql:latest
    container_name: "mysql"
    networks:
      - expense-tracker-network
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Test@123
      MYSQL_DATABASE: expenses_tracker
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pTest@123"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
  expense-app:
    build:
      context: .
    image: expense-app:latest
    container_name: "expense-app"
    environment:
      SPRING.DATASOURCE.URL: "jdbc:mysql://mysql:3306/expenses_tracker?allowPublicKeyRetrieval=true&useSSL=false"
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: Test@123

    networks:
      - expense-tracker-network
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  expense-tracker-network:
    driver: bridge
volumes:
  db_data:
    
